"""add catalog, lab, scheduling, telemedicine, maternity tables

Revision ID: b03f584e98dc
Revises: 309f33eb31e5
Create Date: 2026-07-28 13:02:52.819744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03f584e98dc'
down_revision: Union[str, None] = '309f33eb31e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anc_visits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('pregnancy_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('weeks', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('systolic', sa.Integer(), nullable=True),
    sa.Column('diastolic', sa.Integer(), nullable=True),
    sa.Column('fundal_height', sa.Float(), nullable=True),
    sa.Column('hemoglobin', sa.Float(), nullable=True),
    sa.Column('fetal_heart_rate', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anc_visits_hospital_id'), 'anc_visits', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_anc_visits_patient_id'), 'anc_visits', ['patient_id'], unique=False)
    op.create_index(op.f('ix_anc_visits_pregnancy_id'), 'anc_visits', ['pregnancy_id'], unique=False)
    op.create_table('babies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('mother_patient_id', sa.String(), nullable=False),
    sa.Column('pregnancy_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('birth_weight', sa.Float(), nullable=True),
    sa.Column('birth_length', sa.Float(), nullable=True),
    sa.Column('head_circumference', sa.Float(), nullable=True),
    sa.Column('delivery_type', sa.String(), nullable=True),
    sa.Column('gestational_weeks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_babies_hospital_id'), 'babies', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_babies_mother_patient_id'), 'babies', ['mother_patient_id'], unique=False)
    op.create_table('growth_measurements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('baby_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('head_circumference', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_measurements_baby_id'), 'growth_measurements', ['baby_id'], unique=False)
    op.create_index(op.f('ix_growth_measurements_hospital_id'), 'growth_measurements', ['hospital_id'], unique=False)
    op.create_table('immunizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('baby_id', sa.String(), nullable=False),
    sa.Column('vaccine', sa.String(), nullable=False),
    sa.Column('age_label', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('given_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_immunizations_baby_id'), 'immunizations', ['baby_id'], unique=False)
    op.create_index(op.f('ix_immunizations_hospital_id'), 'immunizations', ['hospital_id'], unique=False)
    op.create_table('lab_tests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sample_type', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('turnaround_time', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_tests_hospital_id'), 'lab_tests', ['hospital_id'], unique=False)
    op.create_table('medicines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_hospital_id'), 'medicines', ['hospital_id'], unique=False)
    op.create_table('pregnancy_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('lmp', sa.String(), nullable=False),
    sa.Column('edd', sa.String(), nullable=False),
    sa.Column('gravida', sa.Integer(), nullable=True),
    sa.Column('para', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('pre_pregnancy_weight', sa.Float(), nullable=True),
    sa.Column('blood_group', sa.String(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pregnancy_records_hospital_id'), 'pregnancy_records', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_pregnancy_records_patient_id'), 'pregnancy_records', ['patient_id'], unique=False)
    op.create_table('schedule_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_blocks_doctor_id'), 'schedule_blocks', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_schedule_blocks_hospital_id'), 'schedule_blocks', ['hospital_id'], unique=False)
    op.create_table('test_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('appointment_id', sa.String(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('clinical_note', sa.Text(), nullable=True),
    sa.Column('ordered_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_orders_doctor_id'), 'test_orders', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_test_orders_hospital_id'), 'test_orders', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_test_orders_patient_id'), 'test_orders', ['patient_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('reported_by', sa.String(), nullable=True),
    sa.Column('reported_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_hospital_id'), 'test_results', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_test_results_order_id'), 'test_results', ['order_id'], unique=False)
    op.create_table('video_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hospital_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('appointment_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_slots_doctor_id'), 'video_slots', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_video_slots_hospital_id'), 'video_slots', ['hospital_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_slots_hospital_id'), table_name='video_slots')
    op.drop_index(op.f('ix_video_slots_doctor_id'), table_name='video_slots')
    op.drop_table('video_slots')
    op.drop_index(op.f('ix_test_results_order_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_hospital_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_test_orders_patient_id'), table_name='test_orders')
    op.drop_index(op.f('ix_test_orders_hospital_id'), table_name='test_orders')
    op.drop_index(op.f('ix_test_orders_doctor_id'), table_name='test_orders')
    op.drop_table('test_orders')
    op.drop_index(op.f('ix_schedule_blocks_hospital_id'), table_name='schedule_blocks')
    op.drop_index(op.f('ix_schedule_blocks_doctor_id'), table_name='schedule_blocks')
    op.drop_table('schedule_blocks')
    op.drop_index(op.f('ix_pregnancy_records_patient_id'), table_name='pregnancy_records')
    op.drop_index(op.f('ix_pregnancy_records_hospital_id'), table_name='pregnancy_records')
    op.drop_table('pregnancy_records')
    op.drop_index(op.f('ix_medicines_hospital_id'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index(op.f('ix_lab_tests_hospital_id'), table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index(op.f('ix_immunizations_hospital_id'), table_name='immunizations')
    op.drop_index(op.f('ix_immunizations_baby_id'), table_name='immunizations')
    op.drop_table('immunizations')
    op.drop_index(op.f('ix_growth_measurements_hospital_id'), table_name='growth_measurements')
    op.drop_index(op.f('ix_growth_measurements_baby_id'), table_name='growth_measurements')
    op.drop_table('growth_measurements')
    op.drop_index(op.f('ix_babies_mother_patient_id'), table_name='babies')
    op.drop_index(op.f('ix_babies_hospital_id'), table_name='babies')
    op.drop_table('babies')
    op.drop_index(op.f('ix_anc_visits_pregnancy_id'), table_name='anc_visits')
    op.drop_index(op.f('ix_anc_visits_patient_id'), table_name='anc_visits')
    op.drop_index(op.f('ix_anc_visits_hospital_id'), table_name='anc_visits')
    op.drop_table('anc_visits')
    # ### end Alembic commands ###
